# Generated by Django 4.1.7 on 2023-03-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2app', '0003_alter_members_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=850),
        ),
    ]
